name: Daily Commit

on:
  schedule:
    - cron: '30 2 * * *'  # Runs daily at 02:30 UTC
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Ensure GitHub Actions can push changes

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git User
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "23f2003511@ds.study.iitm.ac.in"
          git config --list  # Debugging: Verify config

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make a Change
        run: |
          echo "Last run: $(date)" > last_run.txt  # Always modify the file

      - name: Commit and Push Changes
        run: |
          git add last_run.txt
          git commit --author="GitHub Action <23f2003511@ds.study.iitm.ac.in>" -m "Automated daily commit at $(date)" || echo "No changes to commit"
          git push
